// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"github.com/prasetyowira/sweep/internal/app/sweep/product/productadapter/ent/product"

	"github.com/facebookincubator/ent/dialect/sql/schema"
	"github.com/facebookincubator/ent/schema/field"
)

var (
	// ProductsColumns holds the columns for the "products" table.
	ProductsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "uid", Type: field.TypeString, Unique: true, Size: 26},
		{Name: "sku", Type: field.TypeString, Unique: true, Size: 190},
		{Name: "name", Type: field.TypeString, Size: 255},
		{Name: "expirable", Type: field.TypeBool, Default: product.DefaultExpirable},
		{Name: "is_deleted", Type: field.TypeBool, Default: product.DefaultIsDeleted},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// ProductsTable holds the schema information for the "products" table.
	ProductsTable = &schema.Table{
		Name:        "products",
		Columns:     ProductsColumns,
		PrimaryKey:  []*schema.Column{ProductsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ProductsTable,
	}
)

func init() {
}
