/*
 * Sweep API
 *
 * Manage Product
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

type CreateProductResponse struct {

	Id string `json:"id"`
}
