/*
 * Sweep API
 *
 * Manage Product
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

type Product struct {

	Id string `json:"id"`

	Sku string `json:"sku"`

	Name string `json:"name"`

	Expirable bool `json:"expirable"`
}
