/*
 * Sweep API
 *
 * Manage Product
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

type ProudctList struct {

	Products []Product `json:"products,omitempty"`
}
